# Generated by Django 5.0.6 on 2024-09-23 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_comments_created_date_alter_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 9, 56, 33, 583566, tzinfo=datetime.timezone.utc)),
        ),
    ]
