# Generated by Django 5.0.6 on 2024-09-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_post_post_image_delete_postfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
