# Generated by Django 5.0.6 on 2024-09-20 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_comments_created_date_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 23, 11, 33, 60309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 23, 11, 33, 60309, tzinfo=datetime.timezone.utc)),
        ),
    ]
