# Generated by Django 5.0.6 on 2024-09-24 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_comments_created_date_postfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 15, 50, 43, 25228, tzinfo=datetime.timezone.utc)),
        ),
    ]
