# Generated by Django 5.0.6 on 2024-09-24 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_post_is_posted_alter_comments_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_posted',
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 15, 54, 53, 535933, tzinfo=datetime.timezone.utc)),
        ),
    ]
