# Generated by Django 5.0.6 on 2024-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_alter_comments_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='image_name',
            field=models.CharField(default='Figure', max_length=256),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
